# Generated by Django 3.1.5 on 2022-01-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='owner',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
