# Generated by Django 3.1.5 on 2022-01-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todoitem_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='owner',
            field=models.TextField(blank=True),
        ),
    ]
